module.exports = [
  'when ama',
  'when is the ama',
  'where is the ama',
  'where ama',
  'wen ama',
  'wen is ama',
  'wen is the ama',
  'wen the ama',
  'when the ama',
  'where will ama',
  'where the ama',
  'where do I see ama',
  'where to see ama',
  'where to get ama',
  'link to ama',
  'what link to ama',
  'ama link',
  'when will the ama',
  'where is the ama',
  'where can I find ama',
  'where to find ama',
  'how to find ama',
  'what is ama',
  'the address of ama',
  'the link of ama',
  'the link to ama',
  'the address to ama',
  'the link for ama',
  'the address for ama',
  'the address of the ama',
  'the link of the ama',
  'the link to the ama',
  'the address to the ama',
  'the link for the ama',
  'the address for the ama',
];
