module.exports = [
  'devs doxxed?',
  'dev doxxed?',
  'team doxxed?',
  'are devs anon',
  'are devs doxxed',
  'plan to doxx?',
  'someone know the team',
  'devs doxed',
  'is the team anon',
  'is the team here anon',
  'is the team here dox',
  'is team here dox',
  'is team dox',
  'is team anon',
  'are developers doxxed',
  'are developers anon',
  'developers doxxed',
  'not doxxed?',
  'do we know anything about this team',
  'do we know anything about team',
  'do we know anything about dev',
];
