module.exports = [
  'is this a rug',
  'is this rug',
  'this project rug',
  'this team rug',
  'devs rug',
  'devs can rug',
  'team can rug',
  'team rug',
  'is titano rug',
  'is titano a rug',
  'is titano legit',
  'is this project legit',
  'when will titano rug',
  'how can I be sure titano is not a rug',
  'how can I be sure titano is not rug',
  "how can I be sure titano is not won't rug",
  'how can I be sure titano is not will not rug',
  'will titano rug',
  'when titano rug',
  'can titano rug',
  'can this be rug'
];
