module.exports = [
  'bricks',
  'cats',
  'frogs',
  'socks',
  'coffee',
  'cheese',
  'nuggets',
  'dirt',
  'pants',
  'DeBussy',
  'tires',
  'sfggsdfgdfg',
  'I just threw up',
  'lmao',
  'crazy pants',
  'buy some more',
  'blinker violation',
  'brick case of mud slaps',
  'chicken flaps',
  'all the beer',
  'canned fried air',
  'boiled tire squeakers',
  'duck that has been turned around',
  'strapon gloves',
  'mystery smelly socks',
  'charred crispy cream',
  'boiled chicken feet',
  'deep fried butt gas',
  'screaming goats',
  'witches without stitches',
  'sandwich without bread',
  'ostrich',
  'sneakers',
  'burger king foot fungus',
  'trash panda',
  'stretched out bowling ball',
  'fisting monkeys',
  'chicken portabello',
  'kentucky fried geese',
  'cabbage cream',
  'war against drug lords',
  'napkins',
  'fried air was an inside job',
  '<https://www.youtube.com/watch?v=iik25wqIuFo>',
];
