module.exports = [
  'insufficient output amount',
  'INSUFFICIENT_OUTPUT_AMOUNT',
  "can't swap titano",
  "can't buy titano",
  "can't sell titano",
  "can't i sell titano",
  "can't i buy titano",
  "can't i swap titano",
  'cant sell titano',
  'cant swap titano',
  'cant buy titano',
  'cant sell titano',
  'cant sell my titano',
  'cant swap my titano',
  'cant buy my titano',
  'cant sell my titano',
  "can't sell my titano",
  "can't swap my titano",
  "can't buy my titano",
  "can't sell my titano",
  'cant i sell titano',
  'cant i buy titano',
  'cant i swap titano',
  "can't I sell my Titano",
  "can't I buy my Titano",
  "can't I swap my Titano",
  'cant I sell my Titano',
  'cant I buy my Titano',
  'cant I swap my Titano',
  'can no longer sell my Titano',
  'can no longer sell Titano',
  'titano not selling',
  'pancakeswap error',
  'error selling',
  'error buying',
  'pancake swap error',
  'getting this error',
  'cant swap',
  'cant buy',
  "can't buy",
  'how buy',
  'how buy titano',
  'how sell',
  'how sell titano',
  'help sell titano',
  'help buy titano',
  'problem with swapping',
  'problem swapping',
  'issues swapping',
  "can't sell my coins",
  "can't sell my titano",
  'cannot sell my titano',
  'can not sell my titano',
  'cannot sell my coins',
  'error on pancakeswap',
  'what is the slippage',
  'what slippage',
  'what is slippage',
  'trying to buy titano',
  'I keep getting error',
  'i get error',
  'i keep getting this error',
  'i get this error',
  'get this error',
  'get error',
  'keep getting error',
  'keep getting this error',
];
