module.exports = [
  'can you guys see the token in your wallet',
  'can you see the token in your wallet',
  "i can't see my tokens",
  "i can't see my token",
  "can't see my tokens",
  "can't see my token",
  "can't see my coin",
  'cant see my coin',
  'cant see my token',
  'where to see my token',
  'where to see my tokens',
  'where do i see my tokens',
  'where do i see my token',
  'where can i see my token',
  'where can i see my tokens',
  'how to add tokens',
  'how to add the tokens',
  'how to add my tokens',
  'how to add titano tokens',
  'how to add token',
  'how to add the token',
  'how to add my token',
  'how to add titano token',
  'do you add it manually',
  'do you add it manually',
  'what do i fill in to see my titano tokens',
];
