module.exports = [
  'how do i stake titano',
  'how do i stake',
  'how stake titano',
  'where to stake titano',
  'do i stake titano',
  'how to stake',
  'where to stake',
  'where stake',
  'how stake',
  'is stake auto',
  'is staking auto',
  'does stake auto',
  'is staking automatic',
  'is titano staking automatically',
  'cant stake titano',
  'cant stake my titano',
  'cant stake',
  "can't stake my titano",
  'cant stake titano',
  "can't stake my titano",
  "can't stake",
  'need help staking',
  'help staking',
  'is auto stake?',
  'do i need to stake',
  'where do i stake',
];
