module.exports = [
  'where to buy titano',
  'where to buy titano?',
  'where can i  buy titano',
  'where can i  buy titano?',
  'how to buy titano',
  'how to buy titano?',
  'how can i buy titano',
  'how can i buy titano?',
  'where buy titano',
  'where buy titano?',
  'where can I buy titano',
  'where can I buy titano?',
  'how can i get titano',
  'how can i get titano?',
  'how getting titano',
  'how getting titano?',
  'how to get titano',
  'how to get titano?',
  'how do i swap into titano',
  'how do i swap into titano?',
  'how swap into titano',
  'how swap into titano?',
  'how do i swap Titano token',
  'how do i swap Titano token?',
  'how to swap Titano token',
  'how to swap Titano token?',
  'how do i swap Titano coin',
  'how do i swap Titano coin?',
  'how to swap Titano coin',
  'how to swap Titano coin?',
  'where i can sell Titano',
  'where i can sell Titano?',
  'where can i sell Titano',
  'where can i sell Titano?',
  'where i can sell Titano',
  'where i can sell Titano?',
];
