module.exports = [
  'what is migration',
  'when migration',
  'what is a migration',
  'what migration',
  'how will the migration work',
  'what is happening with a migration',
  'when will migration happen',
  'what the migration is going to look',
  'When does the team plan to migrate to the new contract',
  'what are we expecting for the contract migration',
  'would we have to do anything with our tokens',
  'how will the migration look',
  'What do we have to do to migrate',
  'will we have to do something for migration',
  'are we migrating tokens',
  'why are we migrating',
  'why migration',
  'why migrate',
  'are we migrating',
  'when we migrating',
  'why do we migrate',
  'why do we need to migrate',
  'why do we need the migration',
  'why new token',
  'why the new token',
  'will there be new token',
  'will there be a new token',
  'when titano v2',
  'why titano v2',
  'what will the migration change',
  'what will change in new contract',
  'When is migration',
  'why are we doing V2',
  'What is this titano v2',
  'What is the migration',
];
