module.exports = [
  '100% selling fee',
  '100% sell fee',
  'can increase the fees up to 100%',
  'may increase the fees up to 100%',
  'owner may adjust the fees to any value, up to 100%, at any time',
  'owner may adjust the fees to any value',
  'up to 100%, at any time',
  'fees can be changed by devs to 100%?',
  'changed by devs to 100%',
  'selling fees to 100%',
  'selling fee to 100%',
  'sell fee to 100%',
  'dev team can change the fees at anytime',
  'without notice to 100%',
  'devs can adjust fees to 100%',
  'devs can adjust the fees to 100%',
  'devs can increase fees to 100%',
  'devs can increase the fees to 100%',
  'they can adjust fees to 100%',
  'they can adjust the fees to 100%',
  'they can increase fees to 100%',
  'they can increase the fees to 100%',
  'team can adjust fees to 100%',
  'team can adjust the fees to 100%',
  'team can increase fees to 100%',
  'team can increase the fees to 100%',
  'devs can stop us from selling',
  'owner can increase fees',
];
